### ISSUE TITLE
Script Fails to Run

### ISSUE THREAD

**Issue by Kiwifuit** [wodxgod/Discord-Token-Grabber#47]
Hello

I copied the contents of the file and changed the `WEBHOOK_URL` variable into the webhook that I made. I also changed the `PING_ME` variable to True.

When I run the script, it gives me a `FileNotFound` error, so I tried to fix it by adding ` or FileNotFoundError` in Line 45 so it looks like this:
```py
    for platform, path in paths.items():
        if not os.path.exists(path) or FileNotFoundError:
            continue
```

All it did was ping me. It did not give me the error.

Error Message (full):
```
Traceback (most recent call last):
  File "c:\Users\Kiwifruit\Documents\Scripts\Python\Console-Based\TokenGrabber\main.py", line 74, in <module>
    main()
  File "c:\Users\Kiwifruit\Documents\Scripts\Python\Console-Based\TokenGrabber\main.py", line 50, in main
    tokens = find_tokens(path)
  File "c:\Users\Kiwifruit\Documents\Scripts\Python\Console-Based\TokenGrabber\main.py", line 18, in find_tokens
    for file_name in os.listdir(path):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Kiwifruit\\AppData\\Roaming\\Opera Software\\Opera Stable\\Local Storage\\leveldb'
```

Any way to fix this?

**Comment by dragneel7xx** [comment]
yup

**Comment by ueahf** [comment]
> yup

love how you say "yup" and not say how lol

**Comment by Kiwifuit** [comment]
lmao
